name: RuboCop

on:
  push:
    branches: [develop, main]
  pull_request:
    branches: [main, develop]

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - name: Set up Ruby
        uses: ruby/setup-ruby@v1
        with:
          ruby-version: 3.0

      - name: Bundle Install
        run: bundle install
      - name: Run RuboCop
        run: bundle exec rubocop
